# Generated by Django 5.2.13 on 2026-05-25 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('1-0', '1-0'), ('0-1', '0-1'), ('1/2-1/2', '1/2-1/2')], max_length=8)),
                ('termination', models.CharField(choices=[('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('draw_agreement', 'Draw Agreement'), ('insufficient_material', 'Insufficient Material'), ('fifty_move_rule', 'Fifty Move Rule'), ('threefold_repetition', 'Threefold Repetition'), ('resignation', 'Resignation'), ('timeout', 'Timeout'), ('abandoned', 'Abandoned')], max_length=32)),
                ('rated', models.BooleanField(default=True)),
                ('rating_category', models.CharField(blank=True, choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('puzzle', 'Puzzle')], max_length=16, null=True)),
                ('initial_time_ms', models.PositiveIntegerField()),
                ('increment_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ended_at', models.DateTimeField()),
                ('move_count', models.PositiveIntegerField(default=0)),
                ('fen_final', models.CharField(max_length=255)),
                ('pgn', models.TextField()),
                ('white_rating_before', models.IntegerField(blank=True, null=True)),
                ('white_rating_after', models.IntegerField(blank=True, null=True)),
                ('white_rating_delta', models.IntegerField(blank=True, null=True)),
                ('black_rating_before', models.IntegerField(blank=True, null=True)),
                ('black_rating_after', models.IntegerField(blank=True, null=True)),
                ('black_rating_delta', models.IntegerField(blank=True, null=True)),
                ('rating_applied_at', models.DateTimeField(blank=True, null=True)),
                ('black_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_games', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='games_game_started_2cd822_idx'), models.Index(fields=['white_player'], name='games_game_white_p_6b87d6_idx'), models.Index(fields=['black_player'], name='games_game_black_p_ccce12_idx'), models.Index(fields=['rated', 'rating_category'], name='games_game_rated_d0dfa0_idx')],
            },
        ),
    ]
