# Generated by Django 5.2.14 on 2026-07-14 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_started_2cd822_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-started_at', '-id'], name='games_game_started_8659ee_idx'),
        ),
    ]
