# Generated by Django 5.2.13 on 2026-04-17 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('puzzle', 'Puzzle')], max_length=10)),
                ('value', models.IntegerField(default=1200)),
                ('games_played', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deviation', models.FloatField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'value'], name='ratings_rat_categor_82bdb5_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
