# Generated by Django 5.2.13 on 2026-04-22 19:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='category',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('puzzle', 'Puzzle')], max_length=16),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('game', 'Game'), ('puzzle', 'Puzzle'), ('admin', 'Admin'), ('system', 'System')], max_length=16)),
                ('previous_value', models.IntegerField()),
                ('new_value', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('game_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('opponent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_history_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ratings.rating')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'created_at'], name='ratings_rat_source_34f1ca_idx'), models.Index(fields=['game_id'], name='ratings_rat_game_id_6d966a_idx')],
            },
        ),
    ]
