# Generated by Django 5.2.13 on 2026-05-25 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('ratings', '0002_alter_rating_options_alter_rating_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ratinghistory',
            name='ratings_rat_game_id_6d966a_idx',
        ),
        migrations.RemoveField(
            model_name='ratinghistory',
            name='game_id',
        ),
        migrations.AddField(
            model_name='ratinghistory',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_history_entries', to='games.game'),
        ),
        migrations.AddIndex(
            model_name='ratinghistory',
            index=models.Index(fields=['game'], name='ratings_rat_game_id_6d966a_idx'),
        ),
    ]
